# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render a FasteningPlan as one continuous URScript program covering
every hole in the plan's for_each fastening sequence:

    [load_screw handshake] movej standoff_1 -> movel contact_1 ->
    [drive_screw handshake] -> movel retract_1 ->
    [load_screw handshake] movej standoff_2 -> ... -> movel retract_N ->
    movej home

Transits between holes go directly retract_i -> standoff_{i+1} -- no
return home in between (see .planner.plan's own module docstring).

## load_screw overlap

`load_screw` has no motion block -- the robot doesn't have to be anywhere
in particular for it (sd50's own manifest note: "the generator is free to
overlap this with the robot's move to the next hole"). Its PLC-handshake
placeholder is therefore emitted immediately BEFORE the transit movej that
carries the robot to that hole's standoff, not serially after the
previous hole's retract -- the feed cycle and that motion happen
concurrently on the real cell. For hole 1, that's the home->standoff_1
move -- there is no prior hole to have just retracted from.

## on_fail

`on_fail` (eject_screw / reject_part) is PLC coordinator logic, not
something this robot program executes -- see ADR-0004: the coordinator
sequences modules via PackML, and abort/recovery routing is its job, not a
robot program's. It's noted here as a comment, never emitted as motion.

SI units throughout (metres, radians, m/s -- URScript's own convention)
and real, unnamespaced UR joint names, since this text is meant to run on
an actual UR controller, not inside this package's own namespaced scene
URDF.

No `set_tcp()`: every movel pose targets the FLANGE (tool0), the same
frame `.planner.ik` solved reachability against -- not the screwdriver's
own TCP. The bit ends up in the right place as a direct consequence of the
flange landing correctly, since sd50 is bolted to the flange at a fixed,
known, purely-translational offset; this avoids a second frame convention
(the controller's own active-TCP setting) this v0 doesn't otherwise need
to touch.
"""

from __future__ import annotations

from ocm_generator.planner import UR_JOINT_ORDER, FasteningPlan
from ocm_generator.scene import Pose

_JOINT_NAMES_COMMENT = "  # " + ", ".join(UR_JOINT_ORDER)


def _format_joint_values(joints: tuple[float, ...]) -> str:
    values = ", ".join(f"{v:.6f}" for v in joints)
    return f"[{values}]"


def _format_pose(pose: Pose) -> str:
    x, y, z = pose.translation
    rx, ry, rz = pose.axis_angle()
    return f"p[{x:.6f}, {y:.6f}, {z:.6f}, {rx:.6f}, {ry:.6f}, {rz:.6f}]"


def emit_urscript(plan: FasteningPlan) -> str:
    """URScript text for `plan`'s full home -> (standoff/contact/retract)*N
    -> home sequence. Positions in metres, rotations as axis-angle radians
    (URScript's own `p[x,y,z,rx,ry,rz]` pose convention), speeds in m/s.
    """
    lines = [
        f"# {plan.tool_instance} fastening sequence ({len(plan.holes)} hole(s)) "
        "-- generated by `ocm plan --emit-urscript`",
    ]

    if plan.on_fail_summary:
        lines.append(f"# on_fail ({plan.on_fail_summary}) is PLC-side logic -- not emitted here, see ADR-0004")

    for hole in plan.holes:
        if plan.load_screw_module is not None:
            lines.append("# PLC handshake: load_screw (overlaps following transit)")
        lines.append(f"movej({_format_joint_values(hole.standoff_joints)}){_JOINT_NAMES_COMMENT}")
        lines.append(f"movel({_format_pose(hole.contact_pose_base)}, v={plan.approach_speed_m_s:.6f})")
        lines.append(f"# TODO PLC handshake: drive_screw @ {hole.hole_id}")
        lines.append(f"movel({_format_pose(hole.retract_pose_base)}, v={plan.approach_speed_m_s:.6f})")

    lines.append(f"movej({_format_joint_values(plan.home_joints)}){_JOINT_NAMES_COMMENT}")

    return "\n".join(lines) + "\n"
