# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render a FasteningPlan as one continuous URScript program covering
every hole in the plan's for_each fastening sequence:

    [load_screw handshake] movej standoff_1 -> [sync] -> movel contact_1 ->
    [sync] -> movel retract_1 ->
    [load_screw handshake] movej standoff_2 -> ... -> movel retract_N ->
    movej home

Transits between holes go directly retract_i -> standoff_{i+1} -- no
return home in between (see .planner.plan's own module docstring).

## The spec/08 handshake -- not a comment anymore

Every standoff and every contact is a real sync point implementing
spec/08-robot-handshake.md's step-counter protocol over the `ur-rtde`
binding: the robot writes its arrival (`hs_at_step`), then blocks --
checking `hs_abort` and incrementing `hs_heartbeat` on every iteration --
until the coordinator raises `hs_done_step` to meet it. Step numbers come
from `.planner.poses.standoff_step_number`/`contact_step_number` -- the
SAME functions `.coordinator` uses to number its own wait targets, so the
two programs can never drift out of sync on what step N means. See that
module's docstring, and spec/08 itself, for the full protocol (why it's
level-based not edge-based, why preconditions gate the standoff step
specifically, why abort just halts in place with recovery left to the
coordinator).

`load_screw` has no motion block -- the robot doesn't have to be anywhere
in particular for it (sd50's own manifest note: "the generator is free to
overlap this with the robot's move to the next hole"). Its PLC-handshake
placeholder is therefore emitted immediately BEFORE the transit movej that
carries the robot to that hole's standoff, not serially after the
previous hole's retract -- the feed cycle and that motion happen
concurrently on the real cell. For hole 1, that's the home->standoff_1
move -- there is no prior hole to have just retracted from. It is NOT a
numbered sync point itself: its completion is what the coordinator gates
the FOLLOWING standoff's `hs_done_step` on (drive_screw's own
`screw_present` precondition), not something the robot program waits on
directly.

## on_fail

`on_fail` (eject_screw / reject_part) is PLC coordinator logic, not
something this robot program executes -- see ADR-0004: the coordinator
sequences modules via PackML, and abort/recovery routing is its job, not a
robot program's. It's noted here as a comment, never emitted as motion.
A failed result (`result_ok == false`) reaches the robot as `hs_abort`,
same as any other abort -- see spec/08's Abort section.

SI units throughout (metres, radians, m/s -- URScript's own convention)
and real, unnamespaced UR joint names, since this text is meant to run on
an actual UR controller, not inside this package's own namespaced scene
URDF.

No `set_tcp()`: every movel pose targets the FLANGE (tool0), the same
frame `.planner.ik` solved reachability against -- not the screwdriver's
own TCP. The bit ends up in the right place as a direct consequence of the
flange landing correctly, since sd50 is bolted to the flange at a fixed,
known, purely-translational offset; this avoids a second frame convention
(the controller's own active-TCP setting) this v0 doesn't otherwise need
to touch.
"""

from __future__ import annotations

from ocm_generator.planner import UR_JOINT_ORDER, FasteningPlan, contact_step_number, standoff_step_number
from ocm_generator.scene import Pose

_JOINT_NAMES_COMMENT = "  # " + ", ".join(UR_JOINT_ORDER)

# RTDE general-purpose integer register indices -- spec/08's `ur-rtde` binding.
# Registers 0-1 in each direction are reserved by the spec; 2-23 are free for
# cell-specific use (unused here).
_REG_AT_STEP = 0  # output register: this program writes its arrival
_REG_HEARTBEAT = 1  # output register: this program writes, every wait iteration
_REG_DONE_STEP = 0  # input register: the coordinator writes, level-based (>=)
_REG_ABORT = 1  # input register: the coordinator writes, nonzero => halt in place

_SLEEP_S = 0.05


def _format_joint_values(joints: tuple[float, ...]) -> str:
    values = ", ".join(f"{v:.6f}" for v in joints)
    return f"[{values}]"


def _format_pose(pose: Pose) -> str:
    x, y, z = pose.translation
    rx, ry, rz = pose.axis_angle()
    return f"p[{x:.6f}, {y:.6f}, {z:.6f}, {rx:.6f}, {ry:.6f}, {rz:.6f}]"


def _header(plan: FasteningPlan) -> list[str]:
    lines = [
        f"# {plan.tool_instance} fastening sequence ({len(plan.holes)} hole(s)) "
        "-- generated by `ocm plan --emit-urscript`",
        "#",
        "# spec/08-robot-handshake.md, `ur-rtde` binding. Register map (RTDE",
        "# general-purpose integer registers; registers 0-1 are reserved by the spec):",
        "#   hs_at_step    -> write_output_integer_register(0, N)   -- this program writes",
        "#   hs_heartbeat  -> write_output_integer_register(1, k)   -- this program writes, every wait iteration",
        "#   hs_done_step  -> read_input_integer_register(0)        -- coordinator writes; level-based: wait for >= N",
        "#   hs_abort      -> read_input_integer_register(1)        -- coordinator writes; nonzero => halt in place",
        "# Step numbers are monotonic in plan order, starting at 1: one at each",
        "# hole's standoff (gates the descent to contact on that hole's own",
        "# preconditions, e.g. screw_present) and one at contact (gates leaving",
        "# contact on the drive result, e.g. result_ok). Transit/retract moves",
        "# are not gated.",
        "#",
        "# Every movel pose below targets the FLANGE (tool0) -- no set_tcp() is",
        "# issued. The screwdriver's own TCP offset is a fixed, known translation",
        "# from the flange (sd50's own `tcp` frame), so the bit lands correctly as",
        "# a direct consequence of the flange landing correctly.",
    ]
    if plan.on_fail_summary:
        lines.append("#")
        lines.append(f"# on_fail ({plan.on_fail_summary}) is PLC-side logic -- not emitted here, see ADR-0004")
    return lines


def _sync_block(step: int) -> list[str]:
    """spec/08's step-counter wait: announce arrival at `step`, then block
    -- checking abort and incrementing the heartbeat every iteration --
    until the coordinator raises hs_done_step to meet it. Level-based
    (`< step`, not an edge test), per spec/08's own "immune to missed
    edges, polling jitter, and restarts mid-sequence" rationale.
    """
    return [
        f"write_output_integer_register({_REG_AT_STEP}, {step})",
        f"while read_input_integer_register({_REG_DONE_STEP}) < {step}:",
        f"  if read_input_integer_register({_REG_ABORT}) != 0:",
        "    halt",
        "  end",
        "  hb = hb + 1",
        f"  write_output_integer_register({_REG_HEARTBEAT}, hb)",
        f"  sleep({_SLEEP_S})",
        "end",
    ]


def emit_urscript(plan: FasteningPlan) -> str:
    """URScript text for `plan`'s full home -> (standoff/contact/retract)*N
    -> home sequence, with a real spec/08 handshake sync at every standoff
    and contact. Positions in metres, rotations as axis-angle radians
    (URScript's own `p[x,y,z,rx,ry,rz]` pose convention), speeds in m/s.
    """
    lines = list(_header(plan))
    lines.append("")
    lines.append("hb = 0")
    lines.append("")

    for hole in plan.holes:
        if plan.load_screw_module is not None:
            lines.append("# PLC handshake: load_screw (overlaps following transit)")
        lines.append(f"movej({_format_joint_values(hole.standoff_joints)}){_JOINT_NAMES_COMMENT}")
        standoff_step = standoff_step_number(hole.index)
        lines.append(
            f"# sync: standoff @ {hole.hole_id} (step {standoff_step}) -- "
            "coordinator gates this on drive_screw's own preconditions"
        )
        lines.extend(_sync_block(standoff_step))

        lines.append(f"movel({_format_pose(hole.contact_pose_base)}, v={plan.approach_speed_m_s:.6f})")
        contact_step = contact_step_number(hole.index)
        lines.append(
            f"# sync: contact @ {hole.hole_id} (step {contact_step}) -- "
            "coordinator runs drive_screw and checks result_ok"
        )
        lines.extend(_sync_block(contact_step))

        lines.append(f"movel({_format_pose(hole.retract_pose_base)}, v={plan.approach_speed_m_s:.6f})")

    lines.append(f"movej({_format_joint_values(plan.home_joints)}){_JOINT_NAMES_COMMENT}")

    return "\n".join(lines) + "\n"
