"""Flatten the vendored UR5e config YAML (config/) into a static URDF fragment.

Universal_Robots_ROS2_Description's real URDF is produced by a xacro macro
(ur_macro.xacro) parameterized by these same four YAML files. Running that
macro requires ROS's ament/xacro package-resolution machinery
($(find ur_description)/...), which this repo doesn't have. Rather than fake
a ROS environment, this script does the same substitution ur_macro.xacro
does -- reading the identical vendored YAML data -- and emits a flat URDF
directly. The link/joint chain, names, and origins below are transcribed
from urdf/ur_macro.xacro and urdf/inc/ur_common.xacro (see NOTICE.md for the
exact upstream commit); only the config VALUES are read programmatically,
so re-running this script against a re-vendored (e.g. newer, or per-unit
calibrated) config/ directory reproduces the fragment mechanically rather
than by hand-editing numbers.

Deliberately collision-only: no <visual>/mesh DAE files are vendored (that's
an ocm-viewer concern), so this fragment has no <visual> tags, only
<collision> and <inertial>. Re-run with:

    python generate_flat_urdf.py > ur5e.urdf.xacro
"""

from __future__ import annotations

import math
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CONFIG = HERE / "config"


def _degrees_constructor(loader: yaml.SafeLoader, node: yaml.ScalarNode) -> float:
    return math.radians(float(loader.construct_scalar(node)))


class _Loader(yaml.SafeLoader):
    pass


_Loader.add_constructor("!degrees", _degrees_constructor)


def _load(name: str) -> dict:
    with open(CONFIG / name, "r", encoding="utf-8") as f:
        return yaml.load(f, Loader=_Loader)


def _f(x: float) -> str:
    return f"{x:.10g}"


def _xyz(d: dict) -> str:
    return f"{_f(d['x'])} {_f(d['y'])} {_f(d['z'])}"


def _rpy(d: dict) -> str:
    return f"{_f(d['roll'])} {_f(d['pitch'])} {_f(d['yaw'])}"


def _cylinder_inertia(mass: float, radius: float, length: float) -> tuple[float, float, float]:
    ixx = iyy = 0.0833333 * mass * (3 * radius * radius + length * length)
    izz = 0.5 * mass * radius * radius
    return ixx, iyy, izz


LINKS = ["shoulder", "upper_arm", "forearm", "wrist_1", "wrist_2", "wrist_3"]
JOINT_NAMES = {
    "shoulder": "shoulder_pan_joint",
    "upper_arm": "shoulder_lift_joint",
    "forearm": "elbow_joint",
    "wrist_1": "wrist_1_joint",
    "wrist_2": "wrist_2_joint",
    "wrist_3": "wrist_3_joint",
}
CHAIN_PARENT = {
    "shoulder": "base_link_inertia",
    "upper_arm": "shoulder_link",
    "forearm": "upper_arm_link",
    "wrist_1": "forearm_link",
    "wrist_2": "wrist_1_link",
    "wrist_3": "wrist_2_link",
}
LIMIT_KEY = {
    "shoulder": "shoulder_pan_joint",
    "upper_arm": "shoulder_lift_joint",
    "forearm": "elbow_joint",
    "wrist_1": "wrist_1_joint",
    "wrist_2": "wrist_2_joint",
    "wrist_3": "wrist_3_joint",
}
MESH_NAME = {
    "shoulder": "shoulder",
    "upper_arm": "upperarm",
    "forearm": "forearm",
    "wrist_1": "wrist1",
    "wrist_2": "wrist2",
    "wrist_3": "wrist3",
}


def main() -> None:
    kinematics = _load("default_kinematics.yaml")["kinematics"]
    limits = _load("joint_limits.yaml")["joint_limits"]
    physical = _load("physical_parameters.yaml")["inertia_parameters"]

    base_ixx, base_iyy, base_izz = _cylinder_inertia(
        physical["base_mass"],
        physical["links"]["base"]["radius"],
        physical["links"]["base"]["length"],
    )

    out: list[str] = []
    out.append('<?xml version="1.0"?>')
    # NOTE: XML comments may not contain "--" anywhere in the body, only as
    # the opening/closing delimiters -- keep punctuation to single hyphens.
    out.append(
        '<!--\n'
        '  UR5e kinematic + collision chain, flattened from Universal_Robots_ROS2_Description\n'
        '  (BSD-3-Clause). Generated by generate_flat_urdf.py from the vendored config/*.yaml;\n'
        '  see NOTICE.md for the exact source commit and what was and was not carried over\n'
        '  (no <visual>/DAE meshes; collision STL + kinematics + inertials only).\n'
        '  DO NOT HAND-EDIT: edit config/*.yaml and re-run the generator instead.\n'
        '-->'
    )
    out.append('<robot name="ur5e">')

    # base_link is the fragment's root -- deliberately NOT fixed to a "world"
    # link here. ocm_generator.scene attaches whatever this fragment's root
    # link turns out to be; baking in our own "world" would just create a
    # redundant extra link under the real world link it generates.
    out.append('  <link name="base_link"/>')
    out.append('  <link name="base_link_inertia">')
    out.append('    <collision>')
    out.append(f'      <origin xyz="0 0 0" rpy="0 0 0"/>')
    out.append('      <geometry><mesh filename="../meshes/collision/base.stl"/></geometry>')
    out.append('    </collision>')
    out.append('    <inertial>')
    out.append(f'      <mass value="{_f(physical["base_mass"])}"/>')
    out.append('      <origin xyz="0 0 0" rpy="0 0 0"/>')
    out.append(
        f'      <inertia ixx="{_f(base_ixx)}" ixy="0" ixz="0" '
        f'iyy="{_f(base_iyy)}" iyz="0" izz="{_f(base_izz)}"/>'
    )
    out.append('    </inertial>')
    out.append('  </link>')
    out.append('  <joint name="base_link-base_link_inertia" type="fixed">')
    out.append('    <parent link="base_link"/>')
    out.append('    <child link="base_link_inertia"/>')
    out.append(f'    <origin xyz="0 0 0" rpy="0 0 {_f(math.pi)}"/>')
    out.append('  </joint>')

    for key in LINKS:
        link_name = f"{key}_link"
        cog = physical["center_of_mass"][f"{key}_cog"]
        rot = physical["rotation"][key]
        tensor = physical["tensor"][key]
        mass = physical[f"{key}_mass"]

        out.append(f'  <link name="{link_name}">')
        out.append('    <collision>')
        out.append('      <origin xyz="0 0 0" rpy="0 0 0"/>')
        out.append(f'      <geometry><mesh filename="../meshes/collision/{MESH_NAME[key]}.stl"/></geometry>')
        out.append('    </collision>')
        out.append('    <inertial>')
        out.append(f'      <mass value="{_f(mass)}"/>')
        out.append(f'      <origin xyz="{_xyz(cog)}" rpy="{_rpy(rot)}"/>')
        out.append(
            f'      <inertia ixx="{_f(tensor["ixx"])}" ixy="{_f(tensor["ixy"])}" ixz="{_f(tensor["ixz"])}" '
            f'iyy="{_f(tensor["iyy"])}" iyz="{_f(tensor["iyz"])}" izz="{_f(tensor["izz"])}"/>'
        )
        out.append('    </inertial>')
        out.append('  </link>')

        joint_name = JOINT_NAMES[key]
        parent = CHAIN_PARENT[key]
        origin_xyz = _xyz(kinematics[key])
        origin_rpy = _rpy(kinematics[key])
        lim = limits[LIMIT_KEY[key]]
        joint_type = "revolute"  # ur5e's wrist_3_joint has_position_limits: true (see config/joint_limits.yaml)

        out.append(f'  <joint name="{joint_name}" type="{joint_type}">')
        out.append(f'    <parent link="{parent}"/>')
        out.append(f'    <child link="{link_name}"/>')
        out.append(f'    <origin xyz="{origin_xyz}" rpy="{origin_rpy}"/>')
        out.append('    <axis xyz="0 0 1"/>')
        out.append(
            f'    <limit lower="{_f(lim["min_position"])}" upper="{_f(lim["max_position"])}" '
            f'effort="{_f(lim["max_effort"])}" velocity="{_f(lim["max_velocity"])}"/>'
        )
        out.append('    <dynamics damping="0" friction="0"/>')
        out.append('  </joint>')

    # ROS-Industrial reference frames: force-torque mount, controller 'base'
    # frame, tool flange (== ocm-module's mount.on attachment point), tool0.
    out.append('  <link name="ft_frame"/>')
    out.append('  <joint name="wrist_3_link-ft_frame" type="fixed">')
    out.append('    <parent link="wrist_3_link"/>')
    out.append('    <child link="ft_frame"/>')
    out.append(f'    <origin xyz="0 0 0" rpy="{_f(math.pi)} 0 0"/>')
    out.append('  </joint>')

    out.append('  <link name="base"/>')
    out.append('  <joint name="base_link-base_fixed_joint" type="fixed">')
    out.append('    <parent link="base_link"/>')
    out.append('    <child link="base"/>')
    out.append(f'    <origin xyz="0 0 0" rpy="0 0 {_f(math.pi)}"/>')
    out.append('  </joint>')

    out.append('  <link name="flange"/>')
    out.append('  <joint name="wrist_3-flange" type="fixed">')
    out.append('    <parent link="wrist_3_link"/>')
    out.append('    <child link="flange"/>')
    out.append(f'    <origin xyz="0 0 0" rpy="0 {_f(-math.pi / 2.0)} {_f(-math.pi / 2.0)}"/>')
    out.append('  </joint>')

    out.append('  <link name="tool0"/>')
    out.append('  <joint name="flange-tool0" type="fixed">')
    out.append('    <parent link="flange"/>')
    out.append('    <child link="tool0"/>')
    out.append(f'    <origin xyz="0 0 0" rpy="{_f(math.pi / 2.0)} 0 {_f(math.pi / 2.0)}"/>')
    out.append('  </joint>')

    out.append('</robot>')

    print("\n".join(out))


if __name__ == "__main__":
    main()
