# SPDX-License-Identifier: AGPL-3.0-or-later
"""ocm_core — load and validate OCM module manifests and cell compositions.

The first link in the generator chain (ROADMAP Step 1): scene/, planner/,
and emitters/ all consume a typed Module or Cell instead of walking raw YAML.
"""

from .cell import (
    Base,
    Cell,
    CellSafety,
    Consumable,
    Controller,
    InstanceAddress,
    InstanceMount,
    ModuleInstance,
    ModuleRef,
    Pose,
    validate_cell_dict,
)
from .component import (
    Component,
    ComponentComms,
    ComponentCommsConnector,
    ComponentConnector,
    ComponentElectrical,
    ComponentEnvelope,
    ComponentGeometry,
    ComponentPin,
    ComponentPneumatic,
    ComponentPneumaticPort,
    ComponentSignal,
    ComponentSource,
    ComponentSupply,
)
from .errors import CellLoadError, ManifestValidationError, OcmCoreError
from .loader import load_cell, load_component, load_module, load_schema, validate_module_dict
from .module import (
    Capability,
    Comms,
    ComponentRef,
    Connector,
    Electrical,
    Endpoint,
    Geometry,
    InstancePose,
    Link,
    Maintenance,
    Mechanical,
    Module,
    ModuleComponent,
    Motion,
    Mount,
    Net,
    Nets,
    PathSpec,
    Pin,
    Port,
    Process,
    Safety,
    Signal,
    StateMachine,
    Supply,
    WearItem,
)
from .parameter import Frame, Parameter
from .yaml_rt import new_yaml_rt

__all__ = [
    "Base",
    "Capability",
    "Cell",
    "CellLoadError",
    "CellSafety",
    "Comms",
    "Component",
    "ComponentComms",
    "ComponentCommsConnector",
    "ComponentConnector",
    "ComponentElectrical",
    "ComponentEnvelope",
    "ComponentGeometry",
    "ComponentPin",
    "ComponentPneumatic",
    "ComponentPneumaticPort",
    "ComponentRef",
    "ComponentSignal",
    "ComponentSource",
    "ComponentSupply",
    "Connector",
    "Consumable",
    "Controller",
    "Electrical",
    "Endpoint",
    "Frame",
    "Geometry",
    "InstanceAddress",
    "InstanceMount",
    "InstancePose",
    "Link",
    "Maintenance",
    "ManifestValidationError",
    "Mechanical",
    "Module",
    "ModuleComponent",
    "ModuleInstance",
    "ModuleRef",
    "Motion",
    "Mount",
    "Net",
    "Nets",
    "OcmCoreError",
    "Parameter",
    "PathSpec",
    "Pin",
    "Port",
    "Pose",
    "Process",
    "Safety",
    "Signal",
    "StateMachine",
    "Supply",
    "WearItem",
    "load_cell",
    "load_component",
    "load_module",
    "load_schema",
    "new_yaml_rt",
    "validate_cell_dict",
    "validate_module_dict",
]
